---

engines:
  brakeman:
    enabled: true

  bundler-audit:
    enabled: true

  coffelint:
    enabled: true
    configfile: coffeelint.json

  markdownlint:
    enabled: true

  stylelint:
    enabled: true

    exclude_paths:
      - coverage/**

ratings:
  paths:
    - Gemfile.lock
    - app/**
    - lib/**
    - spec/**
    - config/**
    - db/**
    - "**.coffee"
    - "**.md"
    - "**.scss"
    - "**.rb"
