---

version: "2"

plugins:
  bundler-audit:
    enabled: true

  coffeelint:
    enabled: true
    configfile: coffeelint.json

  markdownlint:
    enabled: true

  stylelint:
    enabled: true

    exclude_paths:
      - "**/*.html"

exclude_patterns:
  - "node_modules/"
  - "coverage/"
  - "tmp/"
