#
# For a complete list of hooks, see:
# https://github.com/causes/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/causes/overcommit#configuration
#
gemfile: Gemfile

#
# Hooks that are run against every commit message after a user has written it.
#
CommitMsg:
  HardTabs:
    enabled: true

  SingleLineSubject:
    enabled: true

  TextWidth:
    enabled: false

  CapitalizedSubject:
    enabled: false

#
# Hooks that are run after `git commit` is executed, before the commit message
# editor is displayed.
#
PreCommit:
  AuthorName:
    enabled: false

  ExecutePermissions:
    enabled: true
    exclude:
      - bin/*

  HardTabs:
    enabled: true

  ImageOptim:
    enabled: true

  LocalPathsInGemfile:
    enabled: true

  MergeConflicts:
    enabled: true

  SlimLint:
    enabled: true
    on_warn: fail

  TrailingWhitespace:
    enabled: true

  YamlSyntax:
    enabled: true
    requires_files: true
