AllCops:
  Include:
    - bin/*

  Exclude:
    - db/schema.rb
    - db/migrate/*.rb

  DisplayCopNames: true

  DisplayStyleGuide: true

  TargetRubyVersion: 2.3

Layout/ExtraSpacing:
  AllowForAlignment: false

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - lib/**/*.rake
    - config/**/*.rb
    - app/admin/**/*.rb

# @todo Until https://github.com/bbatsov/rubocop/pull/4178 merged
Rails/FilePath:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ModuleFunction:
  Enabled: false

Style/FileName:
  Exclude:
    - bin/*
    - Capfile
    - Gemfile
    - Rakefile

Style/Lambda:
  EnforcedStyle: literal

Style/StringLiterals:
  EnforcedStyle: double_quotes

Performance/Casecmp:
  Enabled: false
