---

inherit_mode:
  merge:
    - Include
    - Exclude

AllCops:
  Include:
    - bin/*

  Exclude:
    - db/schema.rb
    - db/migrate/*.rb

  DisplayCopNames: true

  DisplayStyleGuide: true

  TargetRubyVersion: 2.5

Layout/ExtraSpacing:
  AllowForAlignment: false

Rails:
  Enabled: true
  Exclude:
    - bin/*

Rails/FilePath:
  EnforcedStyle: slashes

Metrics:
  Enabled: false

Naming/FileName:
  Exclude:
    - bin/*
    - Capfile
    - Gemfile
    - Rakefile

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - id
    - ip
    - to

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/IfUnlessModifier:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/StringLiterals:
  EnforcedStyle: double_quotes

Performance/Casecmp:
  Enabled: false
