inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
  RunRailsCops: true

  DisplayCopNames: true

  DisplayStyleGuide: true

Style/ModuleFunction:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ExtraSpacing:
  Enabled: true
