AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*.rb

  DisplayCopNames: true

  DisplayStyleGuide: true

  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Style/ModuleFunction:
  Enabled: false

Style/FileName:
  Exclude:
    - bin/*

Style/Lambda:
  Enabled: false

Style/ExtraSpacing:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Performance/Casecmp:
  Enabled: false
