---

version: 2.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-node-browsers

      - image: postgres:9.6.3
        environment:
          POSTGRES_USER: nipanipa

    environment:
      DB_NAME: nipanipa
      DB_PASS: nipanipa

    working_directory: ~/nipanipa

    steps:
      - checkout

      - run: git config --local user.email 'circle@circle.ci'

      - run: git config --local user.name 'Circle CI'

      - run: bundle install

      - run: yarn install

      - run: bin/rake db:create db:migrate

      - run: bin/overcommit --sign

      - run: bin/rake

      - run: bin/overcommit --run

      - run: bin/brakeman

      - add_ssh_keys:
          fingerprints:
            - "4a:6a:34:50:01:b9:3e:e3:5a:44:41:87:1f:47:2e:21"

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              bin/cap production deploy
            fi
