---

- name: Import PgSQL apt key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
           id=ACCC4CF8
           state=present

- name: Add PgSQL apt repo
  apt_repository: >
    repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
    state=present

- name: Install latest PostgreSQL and Ruby bindings
  apt: pkg={{item}} state=latest
  with_items:
    - postgresql-{{pg_version}}
    - libpq-dev
    - python-psycopg2

- name: Create PostgreSQL user for application
  become_user: postgres
  postgresql_user: name={{db_user}}
                   password={{db_pass}}
                   role_attr_flags=CREATEDB

- name: Configure PostgreSQL with md5 authentication
  lineinfile: dest=/etc/postgresql/{{pg_version}}/main/pg_hba.conf
              regexp='^(local  *all  *all  *)'
              line='\1trust'
              backrefs=yes
  register: pgconf

- name: Reload PostgreSQL configuration to pick up the new one
  service: name=postgresql state=reloaded
  when: pgconf.changed
