---

- include: locales.yml tags=locales

- name: Add PostgreSQL repository
  apt_repository: repo='{{pg_apt_repo}}' state=present
  sudo: yes

- name: Add PostgreSQL repository key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
           state=present
           validate_certs=no
  sudo: yes

- name: Update apt cache
  apt: update_cache=yes
  sudo: yes

- name: Install latest PostgreSQL and Ruby bindings
  sudo: yes
  apt: pkg={{item}} state=latest
  with_items:
    - postgresql-{{pg_version}}
    - libpq-dev
    - python-psycopg2

- name: Create PostgreSQL user for application
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{db_user}}
                   password={{db_pass}}
                   role_attr_flags=CREATEDB

- name: Configure PostgreSQL with md5 authentication
  sudo: yes
  lineinfile: dest=/etc/postgresql/{{pg_version}}/main/pg_hba.conf
              regexp='^(local  *all  *all  *)'
              line='\1md5'
              backrefs=yes
  register: pgconf

- name: Reload PostgreSQL configuration to pick up the new one
  sudo: yes
  service: name=postgresql state=reloaded
  when: pgconf.changed
