# Add application configuration variables here, as shown below.

development:
  DB_NAME: nipanipa_development
  MAIL_HOST: localhost:3000
  PAYPAL_HOST: www.sandbox.paypal.com
  PAYPAL_PORT: 443
  PAYPAL_PDT_AT: ihDkGClTsjbX-7eAsFrzOHwyNlSgcArJDCEWI5dl8fMLE1I5dBrIrCzGdqm
  PAYPAL_ACCOUNT: nipa_1359995225_biz@gmail.com

production:
  DB_NAME: nipanipa_production

test:
  DB_NAME: nipanipa_test
  MAIL_HOST: example.com
  PAYPAL_HOST: localhost
  PAYPAL_PORT: 5678
  PAYPAL_PDT_AT: pdtidentitytoken
  PAYPAL_ACCOUNT: test@example.com
