connection: &connection
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  password: <%= ENV["DB_PASS"] %>
  pool: 5
  timeout: 5000
  template: template0
  username: <%= ENV["DB_USER"] %>

development:
  database: nipanipa_development

  <<: *connection

test:
  database: nipanipa_test

  <<: *connection

production:
  database: <%= ENV["DB_NAME"] %>

  <<: *connection
