connection: &connection
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: <%= ENV["DB_NAME"] %>
  password: <%= ENV["DB_PASS"] %>
  pool: 5
  timeout: 5000
  template: template0
  username: <%= ENV["DB_USER"] %>

development:
  <<: *connection

test:
  <<: *connection

production:
  <<: *connection
