# The "main" locale.
base_locale: en

# Read and write translations.
data:
  ## Translations are read from the file system. Supported format: YAML, JSON.
  ## Provide a custom adapter:
  # adapter: I18n::Tasks::Data::FileSystem

  # Locale files or `File.find` patterns where translations are read from:
  read:
    - config/locales/%{locale}/*.yml

  # Locale files to write new keys to, based on a list of key pattern => file
  # rules. Matched from top to bottom: `i18n-tasks normalize -p` will force move
  # the keys according to these rules
  write:
    - ['{devise, simple_form}.*', 'config/locales/%{locale}/\1.yml']
    - config/locales/%{locale}/%{locale}.yml

  yaml:
    write:
      line_width: 80

# Find translate calls
#
search:
  # Paths or `File.find` patterns to search in:
  #
  # paths:
  #  - app/

  # Root directories for relative keys resolution.
  #
  # relative_roots:
  #   - app/controllers
  #   - app/helpers
  #   - app/mailers
  #   - app/presenters
  #   - app/views

  # Files or `File.fnmatch` patterns to exclude from search. Some files are
  # always excluded regardless of this setting: %w(*.jpg *.png *.gif *.svg
  #  *.ico *.eot *.otf *.ttf *.woff *.woff2 *.pdf *.css *.sass *.scss *.less
  # *.yml *.json)
  #
  exclude:
    - app/assets/images
    - app/assets/fonts

  #
  # Don't guess usages such as t("categories.#{category}.title").
  strict: true

# Do not consider these keys missing:
ignore_missing:
  - date.*

# Consider these keys used:
ignore_unused:
  - activerecord.*
  - devise.*
  - enumerize.*
  - helpers.submit.*
  - languages.*
  - views.pagination.*
  - simple_form.{yes,no}
  - simple_form.{placeholders,hints,labels}.*
  - simple_form.{error_notification,required}.*
  - users.*.*_{host,volunteer}
